name: ArtRamen
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  lightness: 0
  brandStrength: 0
  brandColors:
    - '#FAFBFB'
    - '#AB9AE8'
    - '#6C31D8'
    - '#80FCD8'
    - '#4B87EA'
  rhythmicContrast: 0
typography_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
layout_spectrum: 1
