name: ArtRamen
favicon: null
layout_spectrum: 0.71538
typography_spectrum: 0.97077
title: Art that makes you happy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#6f36d9'
    - '#937bdf'
    - '#2500ca'
    - '#82fed8'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.1308138440363109
  rhythmicContrast: 1
purpose: []
